/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditReport {
  'url' : string,
  'overallScore' : bigint,
  'onPageScore' : bigint,
  'recommendations' : Array<string>,
  'pageSpeedScore' : bigint,
  'metaTagsScore' : bigint,
  'technicalScore' : bigint,
  'mobileFriendlinessScore' : bigint,
  'backlinkScore' : bigint,
}
export type AuditResult = { 'ok' : AuditReport } |
  { 'err' : string };
export interface Lead {
  'id' : LeadId,
  'fullName' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export type LeadId = bigint;
export interface LeadInput {
  'fullName' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export type SubmitLeadResult = { 'ok' : LeadId } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'runSeoAudit' : ActorMethod<[string], AuditResult>,
  'submitLead' : ActorMethod<[LeadInput], SubmitLeadResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];