/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditReport {
  'url' : string,
  'overallScore' : bigint,
  'onPageScore' : bigint,
  'recommendations' : Array<string>,
  'pageSpeedScore' : bigint,
  'metaTagsScore' : bigint,
  'technicalScore' : bigint,
  'mobileFriendlinessScore' : bigint,
  'backlinkScore' : bigint,
}
export type AuditResult = { 'ok' : AuditReport } |
  { 'err' : string };
export interface CheckoutRequest {
  'isInstantPayment' : boolean,
  'plan' : PlanType,
}
export interface CheckoutSessionData {
  'isSubscription' : boolean,
  'isInstantPayment' : boolean,
  'trialDays' : bigint,
  'discountedAmountCents' : bigint,
  'amountCents' : bigint,
  'orderId' : string,
  'sessionId' : string,
  'planName' : string,
  'planType' : PlanType,
}
export type CheckoutSessionResult = { 'ok' : CheckoutSessionData } |
  { 'err' : string };
export type GetSubscriptionResult = { 'ok' : SubscriptionView } |
  { 'notFound' : null };
export interface Lead {
  'id' : LeadId,
  'fullName' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export type LeadId = bigint;
export interface LeadInput {
  'fullName' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export type PaymentMethod = { 'stripe' : null };
export type PlanType = { 'webDesign' : null } |
  { 'enterprise' : null } |
  { 'starter' : null } |
  { 'professional' : null };
export type SubmitLeadResult = { 'ok' : LeadId } |
  { 'err' : string };
export type SubscriptionStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'cancelled' : null } |
  { 'pastDue' : null };
export interface SubscriptionView {
  'status' : SubscriptionStatus,
  'nextBillingDate' : Timestamp,
  'trialEndDate' : Timestamp,
  'isInstantPayment' : boolean,
  'createdAt' : Timestamp,
  'discountedAmountCents' : bigint,
  'amountCents' : bigint,
  'stripeSessionId' : [] | [string],
  'trialStartDate' : Timestamp,
  'planName' : string,
  'planType' : PlanType,
}
export type Timestamp = bigint;
export type TransactionStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export interface TransactionView {
  'status' : TransactionStatus,
  'paymentMethod' : PaymentMethod,
  'amountCents' : bigint,
  'orderId' : string,
  'timestamp' : Timestamp,
  'stripeSessionId' : [] | [string],
  'planName' : string,
  'planType' : PlanType,
}
export interface _SERVICE {
  'cancelSubscription' : ActorMethod<[], boolean>,
  'confirmPayment' : ActorMethod<[string], boolean>,
  'createCheckoutSession' : ActorMethod<
    [CheckoutRequest],
    CheckoutSessionResult
  >,
  'getAllTransactions' : ActorMethod<[], Array<TransactionView>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getMyTransactions' : ActorMethod<[], Array<TransactionView>>,
  'getSubscription' : ActorMethod<[], GetSubscriptionResult>,
  'runSeoAudit' : ActorMethod<[string], AuditResult>,
  'submitLead' : ActorMethod<[LeadInput], SubmitLeadResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];