/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Lead = IDL.Record({
  'id' : LeadId,
  'fullName' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const AuditReport = IDL.Record({
  'url' : IDL.Text,
  'overallScore' : IDL.Nat,
  'onPageScore' : IDL.Nat,
  'recommendations' : IDL.Vec(IDL.Text),
  'pageSpeedScore' : IDL.Nat,
  'metaTagsScore' : IDL.Nat,
  'technicalScore' : IDL.Nat,
  'mobileFriendlinessScore' : IDL.Nat,
  'backlinkScore' : IDL.Nat,
});
export const AuditResult = IDL.Variant({
  'ok' : AuditReport,
  'err' : IDL.Text,
});
export const LeadInput = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitLeadResult = IDL.Variant({
  'ok' : LeadId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], []),
  'runSeoAudit' : IDL.Func([IDL.Text], [AuditResult], []),
  'submitLead' : IDL.Func([LeadInput], [SubmitLeadResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Lead = IDL.Record({
    'id' : LeadId,
    'fullName' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AuditReport = IDL.Record({
    'url' : IDL.Text,
    'overallScore' : IDL.Nat,
    'onPageScore' : IDL.Nat,
    'recommendations' : IDL.Vec(IDL.Text),
    'pageSpeedScore' : IDL.Nat,
    'metaTagsScore' : IDL.Nat,
    'technicalScore' : IDL.Nat,
    'mobileFriendlinessScore' : IDL.Nat,
    'backlinkScore' : IDL.Nat,
  });
  const AuditResult = IDL.Variant({ 'ok' : AuditReport, 'err' : IDL.Text });
  const LeadInput = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitLeadResult = IDL.Variant({ 'ok' : LeadId, 'err' : IDL.Text });
  
  return IDL.Service({
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], []),
    'runSeoAudit' : IDL.Func([IDL.Text], [AuditResult], []),
    'submitLead' : IDL.Func([LeadInput], [SubmitLeadResult], []),
  });
};

export const init = ({ IDL }) => { return []; };